FROM krecu/php

MAINTAINER Evgen Kretsu <krecu.me@ya.ru>

LABEL Description="Filestorage php-fpm container" Vendor="GosBook Lab" Version="1.0"

WORKDIR /usr/share/nginx/html/filestorage

RUN usermod -u 1000 www-data